version: '3.9'

networks: 
    web_bus:
      external: true

services:
    app:
        image: hkotel/mealie:latest
        env_file: mealie.env
        volumes:
            - /data2/mealie:/app/data
        restart: "unless-stopped"
        labels:
            # traefik
            - traefik.enable=true
            - traefik.docker.network=web_bus

            # traefikv2
            - "traefik.http.routers.mealie.rule=Host(`recipes.ethelred.org`)"
            - "traefik.http.routers.mealie.entrypoints=web-secure"
            - "traefik.http.services.mealie.loadbalancer.server.port=80"
            # - "traefik.http.routers.mealie.middlewares=forward-auth"            
            - "traefik.http.routers.mealie.tls=true"
            - "traefik.http.routers.mealie.tls.certresolver=default"

        networks:
            - web_bus
      